version: '3'

services:


  web:
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${BACKENDPORT}:8000'
    volumes:
      - ./TycheBackend:/app
      - ./volumes/ApiMedia:/app/media
    env_file: .env
    command: gunicorn --bind 0.0.0.0:8000 TycheBackend.wsgi
    entrypoint: /entrypoint.sh

