# Generated by Django 4.0.3 on 2022-04-15 11:41

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created',
        ),
        migrations.AddField(
            model_name='collection',
            name='WorkArts',
            field=models.ManyToManyField(blank=True, null=True, related_name='Collections', to='Account.workart', verbose_name='WorkArts'),
        ),
        migrations.AlterField(
            model_name='account',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='Account.collection', verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='Account.workart', verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Bannerimage',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='DisplayTheme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Featuredimage',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Logoimage',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
