# Generated by Django 4.0.3 on 2022-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_created_collection_workarts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='WorkArts',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='Account.workart', verbose_name='WorkArts'),
        ),
        migrations.AlterField(
            model_name='workart',
            name='BlockChain',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='workart',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workart',
            name='Externallink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workart',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workart',
            name='Supply',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
