# Generated by Django 4.0.3 on 2022-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_collection_workarts_alter_workart_blockchain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workart',
            name='BlockChain',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
