# Generated by Django 3.2.13 on 2022-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_workart_blockchain_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='Account.collection', verbose_name='members'),
        ),
    ]
