# Generated by Django 4.0.3 on 2022-04-21 08:02

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_account_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='workart',
            name='Liked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to),
        ),
        migrations.AlterField(
            model_name='account',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Bannerimage',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Featuredimage',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Logoimage',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to),
        ),
        migrations.AlterField(
            model_name='workart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Account.models.upload_to),
        ),
    ]
